### ISSUE TITLE
Can I use the library with minsdk 11 for bluetooth beacon and ethernet adapter?

### ISSUE THREAD

**Issue by Sai-Teja** [Blaubot/Blaubot#4]
And I would also like to know the min sdk for multi cast. You are always using min as 16 in your examples!

**Comment by Sai-Teja** [comment]
I would also like to know how to send a message to only selected blaubot device.

**Comment by hgross** [comment]
The minimum sdk version for Blaubot on Android is 16 (see https://github.com/Blaubot/Blaubot/blob/master/blaubot-android/src/main/AndroidManifest.xml). 

If you need 1:1 communication between devices, you can create a channel for each device and maintain a mapping (channelId, Device). For example:

We have three devices A, B, C and they form a network.
- **A** creates and listens on channel **10**
- **B** creates and listens on channel **11**
- **C** creates and listens on channel **12**

To send a message to A, we just send a message through channel 10.
To let the other devices know, which device is listening on which channel, we use channel 1 to send advertisements like "Hey guys, I am device **A** and you can send me messages through **channel 10**"
