### ISSUE TITLE
Android : possibility of wifi only ?

### ISSUE THREAD

**Issue by n0xew** [Blaubot/Blaubot#5]
Hi,
First thanks for this amazing lib!
Secondly, it's not that an issue (or maybe a question worth to add to FAQ), but is it possible to create a Blaubot with only Wifi communication on Android?

I thought I could : 
1. create a wifi hotspot using native Android functionnality; 
2. other devices are supposed to already know this hotspot and connect to it;
3. use blaubot to discover services on this network; 
4. use blaubot once all devices have suscribed to a common channel

So my question is more on part 3, I haven't found yet how to do it or if its possible!

Thanks

**Comment by hgross** [comment]
Hi,

yes, whenever you have an ip-network you can just use the `BlaubotEthernetAdapter` for communication and the `BlaubotBonjourBeacon` for discovery (using mDNS-SD).

To answer your points:
1. You can create such a network programmatically using something like https://github.com/mvdan/accesspoint or do this manually via android's settings menu.
2. There is a good wrap-up on how to connect to a WiFi on SO: http://stackoverflow.com/questions/8818290/how-to-connect-to-a-specific-wifi-network-in-android-programmatically
3. As mentioned I would recommend to use the `BlaubotBonjourBeacon`. You can add as many beacons as you like. For example: use the bonjour-beacon but also discover devices through bluetooth or NFC-interactions. Check the examples folder - you can play around with the different technologies using the [blaubot-app](https://github.com/Blaubot/Blaubot/tree/master/examples/blaubot-app), which provides a blaubot instance configurator and the default debug view.
4. The blaubot api remains the same - regardless of the used technology for the actual communication (the blaubot adapter). So you should be safe on this one.

To get started:
Check the [blaubot-chat example](https://github.com/Blaubot/Blaubot/tree/master/examples)'s MainActivity on how to create a blaubot instance that suits your described scenario ([check this line](https://github.com/Blaubot/Blaubot/blob/master/examples/blaubot-chat/src/main/java/eu/hgross/blaubot/example/chat/BlaubotChatActivity.java#L83)).

hope this helps,
cheers

p.s.: 
Don't forget to show us your application when finished. Always nice to add something to the [showcase page](http://blaubot.henning-gross.de/applications.html) ;-)

**Comment by n0xew** [comment]
Didn't ask for so much (really good and detailled answers), thanks!
Looks like I'll defintely give it a try, be sure I'll inform and mention you when its finished! :)
