### ISSUE TITLE
receive my own messages with excludeSender flag in true

### ISSUE THREAD

**Issue by SpotVL** [Blaubot/Blaubot#7]
Good day,

The question is about IBlaubotChannel interface, method boolean publish(byte[] payload, boolean excludeSender). Is excludeSender feature working ?
excludeSender - if true, the message will not be dispatched back to this channel but to all other subscribers.
Because no matter it stands I receive my own messages back.

Thank you for answer and sorry for my bad English (not native language).

**Comment by hgross** [comment]
Hi,

yes, you are right. There seems to be a bug with that option if `transmitReflexiveMessages` is not set to true. As a workaround you can set this option to true on the corresponding channel to achieve the desired behavior:

```
blaubotChannel.getChannelConfig().setTransmitReflexiveMessages(true);
```

This will be fixed soon, thanks for the report!
