### ISSUE TITLE
Question about bluetooth in demo app

### ISSUE THREAD

**Issue by openmotion** [Blaubot/Blaubot#8]
hello
the demo webcam app works only if smartphones are connected in wifi but not in bluetooth. How can i use this app in bluetooth mode or the chat ?
THANK YOU

**Comment by hgross** [comment]
Hello,
I read your additional comments on the matter at gitter (https://gitter.im/Blaubot/Blaubot?at=5871328a9e6f00e74a0a104e). As you found out already, you just have to build a Blaubot instance that fits your needs.

Please note the conceptual difference of discovery and communication in Blaubot. We use one or more technologies to discover devices and exactly one for communication. In your particular use case I assume you want to communicate via Bluetooth. What you actually did using this code

```
mBlaubot = BlaubotAndroidFactory.createEthernetBlaubotWithBluetoothBeacon(APP_UUID, 17171, BlaubotAndroidFactory.getLocalIpAddress());
```

was to discover nearby devices via Bluetooth (classic) but after finding each other, they built a Blaubot-Network using tcp/ip (wifi). 

If you want to create a Blaubot network with bluetooth (only), you would want to use one of the bluetooth related factory methods of [BlaubotAndroidFactory](http://blaubot.henning-gross.de/javadoc/eu/hgross/blaubot/android/BlaubotAndroidFactory.html). 
For example:
* You want to use bluetooth to discover devices and bluetooth to communicate
    * use [BlaubotAndroidFactory.createBluetoothBlaubot](http://blaubot.henning-gross.de/javadoc/eu/hgross/blaubot/android/BlaubotAndroidFactory.html#createBluetoothBlaubot-java.util.UUID-) but note that - because of android restrictions - the devices already have to be paired (you can mitigate that by using another/multiple beacons like nfc, multicast ...)
* You want to use nfc to connect devices with each other and the communicate through bluetooth
    * use [BlaubotAndroidFactory.createBluetoothBlaubotWithNFCBeacon](http://blaubot.henning-gross.de/javadoc/eu/hgross/blaubot/android/BlaubotAndroidFactory.html#createBluetoothBlaubotWithNFCBeacon-java.util.UUID-)
* You want to use bluetooth to automatically discover devices AND you want to be able to initiate connections using nfc (holding devices together)
    * use [BlaubotAndroidFactory.createBluetoothBlaubotWithBluetoothAndNFCBeacon](http://blaubot.henning-gross.de/javadoc/eu/hgross/blaubot/android/BlaubotAndroidFactory.html#createBluetoothBlaubotWithBluetoothAndNFCBeacon-java.util.UUID-)
* You want to discover devices using multicasts through a wifi network but then want communicate through bluetooth
    * use [BlaubotAndroidFactory.createBluetoothBlaubotWithMulticastBeacon](http://blaubot.henning-gross.de/javadoc/eu/hgross/blaubot/android/BlaubotAndroidFactory.html#createBluetoothBlaubotWithMulticastBeacon-java.util.UUID-int-int-)

Of course there are many more possible combinations of Beacons/Adapters. Check out the [documentation on beacons and adapters](http://blaubot.henning-gross.de/documentation/) and the factory functions of [BlaubotAndroidFactory](http://blaubot.henning-gross.de/javadoc/eu/hgross/blaubot/android/BlaubotAndroidFactory.html)
